name: Clang-Tidy

on:
  pull_request:
  push:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy and deps
        run:  sudo apt-get update && sudo apt-get install -y clang-tidy clang cmake build-essential sdl2-dev

      - name: Configure CMake
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build

      - name: Build (optional, but useful for headers)
        run: cmake --build build

      - name: Run clang-tidy
        run: |
          find . -name '*.cpp' | xargs clang-tidy -p build
